### ISSUE TITLE
Question about context of "apply_templates" / ArchivesSpace implementation

### ISSUE THREAD

**Issue by fordmadox** [fidothe/saxon-rb#20]
Not sure if this is related to how this gem (version 0.6.0) is invoked by ArchivesSpace, or something related to how "apply_templates" work, but someone ran into an issue recently where they received an error whenever they defined a global variable in an XSLT file that is utilized by https://github.com/archivesspace/archivesspace/blob/master/backend/app/lib/AS_fop.rb.   

Any ideas why the global variable is failing (or not available globally?).  

Here's a sample error:  

```"The context item for axis step ./ead is absent. Found while atomizing the first argument of fn:subst"```

And here's the global variable that threw that error, which works perfectly fine of course when using saxon directly:

```<xsl:variable name="repo" select="ead:ead/ead:eadheader/ead:filedesc/ead:titlestmt/ead:titleproper/ead:num"/>```

I noticed that there is a "jruby" bug workaround in this gem, so I decided to test a new version of the gem, to see if anything might be different.  However, in that case, I ran into a new error when trying to run "AS_fop.rb":

```NameError uninitialized constant ASFop::Saxon ["org/jruby/RubyModule.java:3760:in `const_missing'"```

Is the current ASpace code in "AS_fop.rb" not compatible with newer versions of this gem?

**Comment by fidothe** [comment]
This first error is actually because of a change in Saxon itself. I'm not sure when exactly it happened either - I don't have any tests which invoke a stylesheey via apply templates that has a global variable that operates on the document. Basically, the global context item (what counts for `.` in global variables or global params) no longer gets defined automatically. This makes sense for named template or by-function invocations of XSLTs, but I have to say I'm confused by it happening with the standard apply-templates invocation. I think it may be something from the 3.0 spec.

There's a simple workaround - declare the global context item like so:

```ruby
input = processor.XML('input.xml')
result = xslt.apply_templates(input, {
  global_context_item: input
})
```

I clearly need to update the README and API docs about this, and I also need to have a think about whether, for apply-templates, we should just set `global_context_item` for you if you don't set it explicitly.

The second error is weird. It's a namespace error that makes it look like nothing's `require`d `saxon/xslt`.

`require 'saxon-rb'` only worked briefly (before October 2019 it was a no-op), and I made it a no-op again because of some other problems with eager-loading breaking the ability to use your own JAR. It didn't actually fix them, so I should be able to just make it work again (all it does is `require 'saxon'`) and push a new release to make that work again for you.

**Comment by fordmadox** [comment]
Nice, thanks @fidothe !!!  I did try plopping in ```global_context_item: input``` based on your documentation before trying to upgrade the gem, but I must've got something wrong in the AS_fop.rb file, because then I got another error.  

I'll be happy to test out the new release whenever that's ready, and thanks again.

**Comment by fidothe** [comment]
This line: https://github.com/archivesspace/archivesspace/blob/e764428fbe5b5034212161969a15056bd7686ff6/backend/app/lib/AS_fop.rb#L44

Should read: 

```ruby
transformer.apply_templates(input, {
  initial_template_parameters: params, 
  global_context_item: input
}).to_destination(sax_destination)
```

**Comment by fidothe** [comment]
New release is pushed to rubygems now. Give it a few minutes to propagate...

**Comment by fidothe** [comment]
> Should read:
> 
> ```ruby
> transformer.apply_templates(input, {
>   initial_template_parameters: params, 
>   global_context_item: input
> }).to_destination(sax_destination)
> ```

Ah, maybe not. You may need to have parsed the source already and pass an XDM node to as the context item. Let me check.

**Comment by fidothe** [comment]
Yeah, you need to parse the input doc separately. SO, that method should look like:


```ruby
  def to_fo(sax_handler)
    transformer = saxon_processor.xslt_compiler.compile(Saxon::Source.create(File.join(ASUtils.find_base_directory, 'stylesheets', 'as-ead-pdf.xsl')))
    sax_destination = Saxon::S9API::SAXDestination.new(sax_handler)
    input = saxon_processor.document_builder.build(Saxon::Source.create(@source))
    params = {"pdf_image" => @pdf_image}
    transformer.apply_templates(input, {
      initial_template_parameters: params, 
      global_context_item: input
    }).to_destination(sax_destination)
  end
```

I think...

**Comment by fordmadox** [comment]
@fidothe, you got it, thanks!  the only other change I had to made to get the parameters to work was to switch out "initial_template_parameters" with "global_parameters", since that's how the "pdf_image" param is used in the current XSL-FO stylesheet.

Thanks again!
